### ISSUE TITLE
Contest Terms and conditions is giving 404

### ISSUE THREAD

**Issue by AlexandruBuhai** [education/github-university-2020#2]
Contest Terms and Condition is not accessible:
![image](https://user-images.githubusercontent.com/23296075/101522467-f0eb6f80-398f-11eb-83b8-ebf0d39e01d3.png)

**Comment by elisemoe** [comment]
Thanks for letting us know @AlexandruBuhai ! ✨

The link should now be working. You can also download them [here](https://github.com/education/github-university-2020/files/5666265/GitHub.Education.Operation.Univers.ity.Event.Contest.Official.Rules.docx).
