### ISSUE TITLE
GH username with uppercase in it doesn't work

### ISSUE THREAD

**Issue by ApolloZhu** [education/github-university-2020#4]
Update: workaround available, see https://github.com/education/github-university-2020/issues/4#issuecomment-741956393

---

It look like TwilioQuest is currently not handling GH username with upper case letters in it correctly. I (@ApolloZhu) made this pull request https://github.com/twilio-labs/open-pixel-art/pull/3047 but as you can see in the screen shot, Twilio Quest doesn't think so:

<img width="1392" alt="Twilio quest not recognizing that ApolloZhu is the same as apollozhu" src="https://user-images.githubusercontent.com/10842684/101531285-07c69d80-3961-11eb-98e0-50b563e03ba7.png">

I tried to redo the entire quest (twice) and making sure I typed in my GH username with correct casing, but it gets changed to lowercase automatically:

<img width="1392" alt="I type in my username in correct casing" src="https://user-images.githubusercontent.com/10842684/101531839-c256a000-3961-11eb-8616-071f4127d445.png">
<img width="1392" alt="It records my username in lowercase" src="https://user-images.githubusercontent.com/10842684/101531850-c4206380-3961-11eb-83ae-226055dd7273.png">

This is the case for these quests:

- [x] Author Your Contribution / The Flame of Open Source (workaround: https://github.com/education/github-university-2020/issues/4#issuecomment-741956393)
- [x] Open a Pull Request / GitHub Hoodie (workaround: https://github.com/education/github-university-2020/issues/4#issuecomment-741956393)

**Comment by ApolloZhu** [comment]
~~(Also it would be great if someone could merge my two accounts (`Apollo Zhu` and `ApolloZhu`) so I won't accidentally be participating twice~~ I just realized the 2 won't have the same achievements and the rules permits situations like this?, so no rush about merging, but merging them will still be appreciated.

> The entry limit is We have four categories of winners and each participant can be entered in each category one time.

Yes, in the current situation I only qualify for each category once.

> Any attempt by any you to obtain more than the stated number of entries by using multiple/different accounts, identities, registrations, logins, or any other methods will void your entries and you may be disqualified.

1. I didn't realize resetting game data will create two accounts on TwilioQuest
2. I'm only using one GitHub account, @ApolloZhu
3. I reset the game data for filing this bug report, not for trying to obtain an unfair advantage

**Comment by kwhinnery** [comment]
Oof, that is a bummer, I guess our string comparison logic is automatically downcasing usernames. We will look to get a fix out today.

**Comment by ApolloZhu** [comment]
Before this is fixed, Ryan Kubik#9022 on discord pointed out that you can manually edit TQ_GITHUB_USERNAME in TwilioQuest. Go into Settings, Variables, and click the Unlock "button" (kinda hard to find, see screenshot below), then you change your username to correct casing:

<img width="1392" alt="The Unlock button is right above TQ_GITHUB_USERNAME, with text underline" src="https://user-images.githubusercontent.com/10842684/101669807-6141d180-3a20-11eb-9587-78b557f02684.png">

**Comment by kwhinnery** [comment]
A fix for this will land in release 3.1.41 - it should show up as a release candidate in the next few minutes in the Launcher, and will be the new stable version in the next day or so!
