### ISSUE TITLE
git command line tools

### ISSUE THREAD

**Issue by DebugAgrawal** [education/github-university-2020#5]
### I've configured the git locally , but I'm unable to go to next level

![Screenshot (533)](https://user-images.githubusercontent.com/64848982/101533711-28701100-39bc-11eb-9925-ce22773cf2da.png)

#### need help with it

**Comment by kwhinnery** [comment]
@DebugAgrawal heya - I see you started a thread on this issue in the TwilioQuest Slack - let's continue to debug there. We will try and get to everyone's questions today.

**Comment by DebugAgrawal** [comment]
> @DebugAgrawal heya - I see you started a thread on this issue in the TwilioQuest Slack - let's continue to debug there. We will try and get to everyone's questions today.

Okay sure👍😊
